# Generated by Django 3.0.1 on 2020-08-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcafeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='image',
            field=models.ImageField(blank=True, default='static/users/userDefault1.png', null=True, upload_to='static/users', verbose_name='Avatar'),
        ),
    ]
