# Generated by Django 3.0.1 on 2020-09-01 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webcafeApp', '0002_auto_20200831_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='image',
            field=models.ImageField(default='static/users/userDefault1.png', null=True, upload_to='static/users', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='uui',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
