# Generated by Django 3.0.1 on 2020-09-15 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcafeApp', '0004_galeria_proceso_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/upload', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True, verbose_name='Tipo de Proceso')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Procesos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tipo_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True, verbose_name='Tipo de Producto')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Producto',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='proceso',
            options={'ordering': ['id'], 'verbose_name_plural': 'Procesos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id'], 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='proceso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload', verbose_name='Imagen'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=255, verbose_name='Correo')),
                ('descricpion', models.TextField(verbose_name='Descripcion')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webcafeApp.Contacto', verbose_name='Blog')),
            ],
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webcafeApp.tipo_proceso', verbose_name='Proceso'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webcafeApp.tipo_producto', verbose_name='Producto'),
        ),
    ]
