# Generated by Django 3.0.1 on 2020-09-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcafeApp', '0005_auto_20200915_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proceso',
            old_name='nombre',
            new_name='tipo_proceso',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='tipo_producto',
        ),
    ]
