# Generated by Django 3.0.1 on 2020-09-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcafeApp', '0006_auto_20200915_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_proceso',
            name='nombre',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Tipo de Proceso'),
        ),
        migrations.AlterField(
            model_name='tipo_producto',
            name='nombre',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Tipo de Producto'),
        ),
    ]
