# Generated by Django 3.0.1 on 2020-09-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcafeApp', '0007_auto_20200916_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='descricpion',
            new_name='descripcion',
        ),
    ]
