# Generated by Django 3.0.1 on 2020-09-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcafeApp', '0008_auto_20200916_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Empresa')),
                ('resumen', models.TextField(max_length=1550, verbose_name='Resumen')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='static/upload', verbose_name='Imagen')),
                ('correo', models.EmailField(max_length=150, verbose_name='Correo Principal')),
                ('correo_1', models.EmailField(blank=True, max_length=150, verbose_name='Correo Secundario')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono Principal')),
                ('telefono_2', models.CharField(blank=True, max_length=15, verbose_name='Teléfono Secundario')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('facebook', models.URLField(blank=True, max_length=100, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, max_length=100, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, max_length=100, verbose_name='Instagram')),
            ],
        ),
    ]
